server:
  port: 8081

spring:
  application:
    name: consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: br.com.mendes.kafka.consumer.listener.MensagemDeserializer

topic:
  app_consumer: topic_app_message_kafka